version: '0'
name: 'React-Deno'
services:
  react:
    build:
      context: . #move to the root of folder struct
      dockerfile: /react-app/Dockerfile
    image: react-app-image
    container_name: react-app-container
    volumes:
       - ${PWD-.}/react-app:/usr/src/app/react-app
       - /usr/src/app/react-app/node_modules
    ports:
      - '3000:3000' #for docker to know where to redirect hot module reload queries
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  deno:
    build:
      context: ./deno-backend
      dockerfile: Dockerfile
    image: deno-image
    container_name: deno-container
    ports:
      - "8000:8080"
    environment:
      - PORT=8000
